# Generated by Django 4.2 on 2025-02-03 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_shelf_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shelf',
            name='user',
        ),
    ]
